# Generated by Django 5.2.9 on 2025-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="city",
            field=models.CharField(
                blank=True, help_text="City where the tour is located", max_length=100
            ),
        ),
    ]
