# Generated by Django 5.2.8 on 2025-12-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_tour_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="accessibility_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1-10 rating. 10 is most accessible (flat, short), 1 is least (steep, long)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="metrics_calculated",
            field=models.BooleanField(
                default=False,
                help_text="True if real-world metrics have been calculated via API",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="total_distance",
            field=models.FloatField(default=0.0, help_text="Total distance in meters"),
        ),
        migrations.AddField(
            model_name="tour",
            name="transport_distance",
            field=models.FloatField(
                default=0.0, help_text="Distance covered by public transport in meters"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="walking_distance",
            field=models.FloatField(
                default=0.0, help_text="Distance covered by walking in meters"
            ),
        ),
    ]
