# Generated by Django 5.2.9 on 2025-12-20 21:27

from django.db import migrations
from math import radians, cos, sin, sqrt, atan2


def calculate_distance(lat1, lon1, lat2, lon2):
    """Calculate distance between two coordinates using Haversine formula (returns meters)"""
    R = 6371000  # Earth radius in meters
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c


def seed_tours(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Tour = apps.get_model('tours', 'Tour')
    TourStep = apps.get_model('tours', 'TourStep')

    # Get or create seed user
    creator, _ = User.objects.get_or_create(
        username='seed_creator',
        defaults={
            'email': 'seed_creator@example.com',
            'first_name': 'Tour',
            'last_name': 'Creator'
        }
    )

    tours_data = [
        {
            'title': 'Historic Istanbul Walking Tour',
            'description': 'Explore the rich history of Istanbul through its most iconic landmarks. This walking tour takes you through centuries of Byzantine and Ottoman heritage.',
            'tour_type': 'STORY',
            'category': 'History',
            'difficulty': 'MEDIUM',
            'duration_minutes': 240,
            'city': 'Istanbul',
            'steps': [
                {'title': 'Hagia Sophia', 'description': 'A masterpiece of Byzantine architecture', 'lat': 41.008580, 'lon': 28.980180},
                {'title': 'Blue Mosque', 'description': 'The iconic Sultan Ahmed Mosque', 'lat': 41.005420, 'lon': 28.976800},
                {'title': 'Topkapi Palace', 'description': 'Former residence of Ottoman sultans', 'lat': 41.011480, 'lon': 28.983280},
                {'title': 'Grand Bazaar', 'description': 'One of the oldest covered markets in the world', 'lat': 41.010600, 'lon': 28.968100},
            ]
        },
        {
            'title': 'Eiffel Tower to Louvre',
            'description': 'A romantic walk through Paris, from the Eiffel Tower to the world-famous Louvre Museum.',
            'tour_type': 'STORY',
            'category': 'Culture',
            'difficulty': 'EASY',
            'duration_minutes': 180,
            'city': 'Paris',
            'steps': [
                {'title': 'Eiffel Tower', 'description': 'The iconic iron lattice tower', 'lat': 48.858370, 'lon': 2.294481},
                {'title': 'Trocadéro Gardens', 'description': 'Beautiful gardens with Eiffel Tower view', 'lat': 48.862060, 'lon': 2.287850},
                {'title': 'Arc de Triomphe', 'description': 'Monumental arch honoring French soldiers', 'lat': 48.873790, 'lon': 2.295030},
                {'title': 'Louvre Museum', 'description': 'The world\'s largest art museum', 'lat': 48.860610, 'lon': 2.337644},
            ]
        },
        {
            'title': 'Colosseum Mystery Hunt',
            'description': 'Solve puzzles while exploring ancient Rome. Discover secrets of the Colosseum and Roman Forum.',
            'tour_type': 'PUZZLE',
            'category': 'Adventure',
            'difficulty': 'HARD',
            'duration_minutes': 210,
            'city': 'Rome',
            'steps': [
                {'title': 'Colosseum', 'description': 'Ancient amphitheater and puzzle location', 'lat': 41.890210, 'lon': 12.492231},
                {'title': 'Roman Forum', 'description': 'Center of ancient Roman life', 'lat': 41.892540, 'lon': 12.485290},
                {'title': 'Palatine Hill', 'description': 'Legendary founding place of Rome', 'lat': 41.889020, 'lon': 12.487140},
                {'title': 'Trevi Fountain', 'description': 'Baroque fountain and wishing well', 'lat': 41.900930, 'lon': 12.483130},
            ]
        },
        {
            'title': 'Barcelona Gothic Quarter',
            'description': 'Wander through medieval streets and discover Gothic architecture in Barcelona\'s oldest neighborhood.',
            'tour_type': 'STORY',
            'category': 'Architecture',
            'difficulty': 'EASY',
            'duration_minutes': 150,
            'city': 'Barcelona',
            'steps': [
                {'title': 'Barcelona Cathedral', 'description': 'Gothic cathedral in the heart of the quarter', 'lat': 41.384030, 'lon': 2.176090},
                {'title': 'Plaça Sant Jaume', 'description': 'Historic square and political center', 'lat': 41.382730, 'lon': 2.176560},
                {'title': 'Carrer del Bisbe', 'description': 'Picturesque Gothic bridge street', 'lat': 41.383640, 'lon': 2.175930},
                {'title': 'Plaça Reial', 'description': 'Beautiful arcaded square', 'lat': 41.380310, 'lon': 2.175260},
            ]
        },
        {
            'title': 'Amsterdam Canal Ring',
            'description': 'Cruise the famous canals and explore the UNESCO World Heritage canal district.',
            'tour_type': 'HYBRID',
            'category': 'Culture',
            'difficulty': 'EASY',
            'duration_minutes': 120,
            'city': 'Amsterdam',
            'steps': [
                {'title': 'Anne Frank House', 'description': 'Historic house and museum', 'lat': 52.375210, 'lon': 4.883890},
                {'title': 'Westerkerk', 'description': 'Protestant church with panoramic views', 'lat': 52.374510, 'lon': 4.883960},
                {'title': 'Nine Streets', 'description': 'Charming shopping district', 'lat': 52.371390, 'lon': 4.886110},
                {'title': 'Bloemenmarkt', 'description': 'Floating flower market', 'lat': 52.367520, 'lon': 4.891830},
            ]
        },
        {
            'title': 'London Royal Trail',
            'description': 'Visit the most iconic royal landmarks in London, from Buckingham Palace to the Tower of London.',
            'tour_type': 'STORY',
            'category': 'History',
            'difficulty': 'MEDIUM',
            'duration_minutes': 270,
            'city': 'London',
            'steps': [
                {'title': 'Buckingham Palace', 'description': 'Official residence of the British monarch', 'lat': 51.501480, 'lon': -0.141880},
                {'title': 'Westminster Abbey', 'description': 'Gothic church and coronation venue', 'lat': 51.499420, 'lon': -0.127380},
                {'title': 'Big Ben', 'description': 'Iconic clock tower', 'lat': 51.500729, 'lon': -0.124625},
                {'title': 'Tower Bridge', 'description': 'Famous bascule and suspension bridge', 'lat': 51.505550, 'lon': -0.075406},
                {'title': 'Tower of London', 'description': 'Historic castle and Crown Jewels location', 'lat': 51.508110, 'lon': -0.076110},
            ]
        },
        {
            'title': 'Venice Hidden Gems',
            'description': 'Explore secret corners of Venice away from the tourist crowds.',
            'tour_type': 'STORY',
            'category': 'Culture',
            'difficulty': 'MEDIUM',
            'duration_minutes': 180,
            'city': 'Venice',
            'steps': [
                {'title': 'Rialto Bridge', 'description': 'Famous bridge over the Grand Canal', 'lat': 45.437980, 'lon': 12.335880},
                {'title': 'Campo Santa Maria Formosa', 'description': 'Charming Venetian square', 'lat': 45.437450, 'lon': 12.342260},
                {'title': 'Libreria Acqua Alta', 'description': 'Unique bookstore with books in bathtubs', 'lat': 45.440280, 'lon': 12.342450},
                {'title': 'St. Mark\'s Square', 'description': 'Venice\'s principal public square', 'lat': 45.434160, 'lon': 12.338090},
            ]
        },
        {
            'title': 'Prague Castle Adventure',
            'description': 'Climb to Prague Castle and discover the heart of Czech history.',
            'tour_type': 'HYBRID',
            'category': 'History',
            'difficulty': 'HARD',
            'duration_minutes': 200,
            'city': 'Prague',
            'steps': [
                {'title': 'Charles Bridge', 'description': 'Medieval stone bridge', 'lat': 50.086630, 'lon': 14.411560},
                {'title': 'Lesser Town Square', 'description': 'Historic square below the castle', 'lat': 50.088010, 'lon': 14.403800},
                {'title': 'Prague Castle', 'description': 'Largest ancient castle complex', 'lat': 50.090890, 'lon': 14.400120},
                {'title': 'St. Vitus Cathedral', 'description': 'Gothic masterpiece', 'lat': 50.090720, 'lon': 14.400280},
            ]
        },
        {
            'title': 'Berlin Wall Memorial Tour',
            'description': 'Follow the path of the Berlin Wall and learn about Germany\'s divided past.',
            'tour_type': 'STORY',
            'category': 'History',
            'difficulty': 'EASY',
            'duration_minutes': 150,
            'city': 'Berlin',
            'steps': [
                {'title': 'East Side Gallery', 'description': 'Open-air gallery on Berlin Wall remains', 'lat': 52.505180, 'lon': 13.439550},
                {'title': 'Berlin Wall Memorial', 'description': 'Official memorial site', 'lat': 52.535150, 'lon': 13.389640},
                {'title': 'Brandenburg Gate', 'description': 'Iconic neoclassical monument', 'lat': 52.516270, 'lon': 13.377700},
                {'title': 'Checkpoint Charlie', 'description': 'Famous Cold War crossing point', 'lat': 52.507510, 'lon': 13.390290},
            ]
        },
        {
            'title': 'Vienna Classical Music Tour',
            'description': 'Experience Vienna through the lives and works of great composers.',
            'tour_type': 'STORY',
            'category': 'Music',
            'difficulty': 'EASY',
            'duration_minutes': 165,
            'city': 'Vienna',
            'steps': [
                {'title': 'Mozart\'s House', 'description': 'Where Mozart composed The Marriage of Figaro', 'lat': 48.210180, 'lon': 16.374250},
                {'title': 'St. Stephen\'s Cathedral', 'description': 'Gothic cathedral where Mozart married', 'lat': 48.208490, 'lon': 16.373060},
                {'title': 'Vienna State Opera', 'description': 'World-renowned opera house', 'lat': 48.203040, 'lon': 16.368930},
                {'title': 'Beethoven Memorial', 'description': 'Monument to the great composer', 'lat': 48.200170, 'lon': 16.366890},
            ]
        },
        {
            'title': 'Lisbon Tram 28 Route',
            'description': 'Follow the iconic Tram 28 route through Lisbon\'s historic neighborhoods.',
            'tour_type': 'STORY',
            'category': 'Culture',
            'difficulty': 'MEDIUM',
            'duration_minutes': 195,
            'city': 'Lisbon',
            'steps': [
                {'title': 'Graça Viewpoint', 'description': 'Panoramic view over Lisbon', 'lat': 38.716950, 'lon': -9.131120},
                {'title': 'Alfama District', 'description': 'Oldest district with narrow streets', 'lat': 38.713460, 'lon': -9.130420},
                {'title': 'Lisbon Cathedral', 'description': 'Oldest church in Lisbon', 'lat': 38.709730, 'lon': -9.132880},
                {'title': 'Chiado Square', 'description': 'Cultural heart of Lisbon', 'lat': 38.710820, 'lon': -9.142150},
            ]
        },
        {
            'title': 'Athens Acropolis Walk',
            'description': 'Climb to the Acropolis and explore ancient Greek civilization.',
            'tour_type': 'STORY',
            'category': 'History',
            'difficulty': 'HARD',
            'duration_minutes': 180,
            'city': 'Athens',
            'steps': [
                {'title': 'Acropolis Entrance', 'description': 'Gateway to ancient history', 'lat': 37.971530, 'lon': 23.725780},
                {'title': 'Parthenon', 'description': 'Temple dedicated to Athena', 'lat': 37.971490, 'lon': 23.726630},
                {'title': 'Erechtheion', 'description': 'Temple with famous Caryatid statues', 'lat': 37.972180, 'lon': 23.726440},
                {'title': 'Ancient Agora', 'description': 'Heart of ancient Athens', 'lat': 37.975070, 'lon': 23.722280},
            ]
        },
        {
            'title': 'Dublin Literary Pub Crawl',
            'description': 'Visit pubs frequented by famous Irish writers like Joyce and Wilde.',
            'tour_type': 'HYBRID',
            'category': 'Literature',
            'difficulty': 'EASY',
            'duration_minutes': 135,
            'city': 'Dublin',
            'steps': [
                {'title': 'Trinity College', 'description': 'Home of the Book of Kells', 'lat': 53.343810, 'lon': -6.254220},
                {'title': 'The Duke Pub', 'description': 'Favorite of literary legends', 'lat': 53.343130, 'lon': -6.259170},
                {'title': 'Davy Byrnes', 'description': 'Featured in Joyce\'s Ulysses', 'lat': 53.342070, 'lon': -6.259730},
                {'title': 'Temple Bar', 'description': 'Cultural quarter with pubs', 'lat': 53.345460, 'lon': -6.264680},
            ]
        },
        {
            'title': 'Copenhagen Hygge Experience',
            'description': 'Discover Danish hygge through cozy cafes, parks, and waterfronts.',
            'tour_type': 'STORY',
            'category': 'Culture',
            'difficulty': 'EASY',
            'duration_minutes': 140,
            'city': 'Copenhagen',
            'steps': [
                {'title': 'Nyhavn', 'description': 'Colorful waterfront district', 'lat': 55.679770, 'lon': 12.591100},
                {'title': 'The Little Mermaid', 'description': 'Iconic bronze statue', 'lat': 55.692970, 'lon': 12.599280},
                {'title': 'Rosenborg Castle', 'description': 'Renaissance castle with gardens', 'lat': 55.685870, 'lon': 12.577530},
                {'title': 'Tivoli Gardens', 'description': 'Historic amusement park', 'lat': 55.673590, 'lon': 12.568090},
            ]
        },
        {
            'title': 'Edinburgh Castle to Arthur\'s Seat',
            'description': 'Hike from Edinburgh Castle to the ancient volcano Arthur\'s Seat.',
            'tour_type': 'HYBRID',
            'category': 'Nature',
            'difficulty': 'HARD',
            'duration_minutes': 240,
            'city': 'Edinburgh',
            'steps': [
                {'title': 'Edinburgh Castle', 'description': 'Historic fortress on Castle Rock', 'lat': 55.948610, 'lon': -3.199640},
                {'title': 'Royal Mile', 'description': 'Historic street in Old Town', 'lat': 55.950540, 'lon': -3.188240},
                {'title': 'Holyrood Palace', 'description': 'Official residence in Scotland', 'lat': 55.952650, 'lon': -3.172020},
                {'title': 'Arthur\'s Seat', 'description': 'Ancient volcano summit', 'lat': 55.944320, 'lon': -3.161820},
            ]
        },
        {
            'title': 'Brussels Chocolate Trail',
            'description': 'Sample the finest Belgian chocolates while touring Brussels landmarks.',
            'tour_type': 'STORY',
            'category': 'Food',
            'difficulty': 'EASY',
            'duration_minutes': 120,
            'city': 'Brussels',
            'steps': [
                {'title': 'Grand Place', 'description': 'Central square with guild houses', 'lat': 50.846690, 'lon': 4.352290},
                {'title': 'Manneken Pis', 'description': 'Famous bronze fountain sculpture', 'lat': 50.844980, 'lon': 4.349950},
                {'title': 'Galeries Royales', 'description': 'Elegant shopping arcades', 'lat': 50.847620, 'lon': 4.355150},
                {'title': 'Sablon Square', 'description': 'Antiques and chocolate shops', 'lat': 50.842310, 'lon': 4.357950},
            ]
        },
        {
            'title': 'Stockholm Gamla Stan',
            'description': 'Explore Stockholm\'s Old Town with its medieval alleyways and colorful buildings.',
            'tour_type': 'STORY',
            'category': 'History',
            'difficulty': 'EASY',
            'duration_minutes': 155,
            'city': 'Stockholm',
            'steps': [
                {'title': 'Royal Palace', 'description': 'Official residence of Swedish monarch', 'lat': 59.326740, 'lon': 18.071600},
                {'title': 'Stortorget Square', 'description': 'Oldest square in Stockholm', 'lat': 59.325690, 'lon': 18.071360},
                {'title': 'Nobel Museum', 'description': 'Museum about Nobel Prize', 'lat': 59.325750, 'lon': 18.071080},
                {'title': 'Riddarholmen Church', 'description': 'Medieval church and royal burial site', 'lat': 59.325350, 'lon': 18.064450},
            ]
        },
        {
            'title': 'Budapest Thermal Baths',
            'description': 'Visit historic thermal baths and learn about Budapest\'s spa culture.',
            'tour_type': 'STORY',
            'category': 'Wellness',
            'difficulty': 'EASY',
            'duration_minutes': 160,
            'city': 'Budapest',
            'steps': [
                {'title': 'Széchenyi Baths', 'description': 'Largest thermal bath complex', 'lat': 47.519330, 'lon': 19.081530},
                {'title': 'Heroes\' Square', 'description': 'Major city square', 'lat': 47.514640, 'lon': 19.077690},
                {'title': 'St. Stephen\'s Basilica', 'description': 'Neoclassical basilica', 'lat': 47.501080, 'lon': 19.053690},
                {'title': 'Chain Bridge', 'description': 'Iconic suspension bridge', 'lat': 47.499060, 'lon': 19.043570},
            ]
        },
        {
            'title': 'Krakow Medieval Quest',
            'description': 'Solve medieval puzzles while exploring Krakow\'s historic market square.',
            'tour_type': 'PUZZLE',
            'category': 'Adventure',
            'difficulty': 'MEDIUM',
            'duration_minutes': 175,
            'city': 'Krakow',
            'steps': [
                {'title': 'Main Market Square', 'description': 'Largest medieval square in Europe', 'lat': 50.061730, 'lon': 19.937260},
                {'title': 'St. Mary\'s Basilica', 'description': 'Gothic church with famous altarpiece', 'lat': 50.061890, 'lon': 19.939430},
                {'title': 'Wawel Castle', 'description': 'Royal castle on hill', 'lat': 50.054170, 'lon': 19.935330},
                {'title': 'Kazimierz District', 'description': 'Historic Jewish quarter', 'lat': 50.051710, 'lon': 19.946300},
            ]
        },
        {
            'title': 'Porto Wine Cellars',
            'description': 'Tour the famous port wine cellars and taste Portugal\'s finest wines.',
            'tour_type': 'STORY',
            'category': 'Food',
            'difficulty': 'EASY',
            'duration_minutes': 130,
            'city': 'Porto',
            'steps': [
                {'title': 'Ribeira Square', 'description': 'Historic riverside district', 'lat': 41.140880, 'lon': -8.613830},
                {'title': 'Dom Luís I Bridge', 'description': 'Double-deck metal arch bridge', 'lat': 41.140740, 'lon': -8.610830},
                {'title': 'Vila Nova de Gaia', 'description': 'Port wine cellar district', 'lat': 41.135810, 'lon': -8.613940},
                {'title': 'Porto Cathedral', 'description': 'Romanesque cathedral', 'lat': 41.143080, 'lon': -8.611180},
            ]
        },
    ]

    # Create tours and steps
    for tour_data in tours_data:
        steps_data = tour_data.pop('steps')
        
        # Calculate total distance
        total_distance = 0
        for i in range(len(steps_data) - 1):
            dist = calculate_distance(
                steps_data[i]['lat'], steps_data[i]['lon'],
                steps_data[i + 1]['lat'], steps_data[i + 1]['lon']
            )
            total_distance += dist

        # Create tour
        tour = Tour.objects.create(
            creator=creator,
            status='PUBLISHED',
            total_distance=total_distance,
            metrics_calculated=True,
            **tour_data
        )

        # Create steps
        for order, step_data in enumerate(steps_data, 1):
            TourStep.objects.create(
                tour=tour,
                order=order,
                title=step_data['title'],
                description=step_data['description'],
                latitude=step_data['lat'],
                longitude=step_data['lon']
            )


def reverse_seed(apps, schema_editor):
    Tour = apps.get_model('tours', 'Tour')
    User = apps.get_model('users', 'User')
    
    # Delete all tours created by seed_creator
    Tour.objects.filter(creator__username='seed_creator').delete()
    # Optionally delete the seed user
    User.objects.filter(username='seed_creator').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_elevation_gain_tour_is_circular_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_tours, reverse_seed),
    ]
