# Generated by Django 5.2.9 on 2025-12-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_seed_20_sample_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourstep',
            name='description',
            field=models.TextField(blank=True, help_text='Story content or location description'),
        ),
    ]
