# Generated by Django 5.2.9 on 2025-12-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_tour_elevation_gain_tour_is_circular_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourstep",
            name="description",
            field=models.TextField(
                blank=True, help_text="Story content or location description"
            ),
        ),
    ]
