# Generated by Django 5.2.12 on 2026-04-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_tourstep_latitude_alter_tourstep_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_covers/'),
        ),
    ]
