# Generated by Django 5.2.13 on 2026-04-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0008_tour_cover_image"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Column already exists in DB; only update Django's state
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="tour",
                    name="credit_price",
                    field=models.PositiveIntegerField(default=0),
                ),
            ],
        ),
    ]
