# Generated by Django 5.2.13 on 2026-04-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0008_tour_cover_image_tour_credit_price"),
    ]

    # The `cover_image` column already exists in the database (added by an
    # earlier migration that is no longer in the file tree). This state-only
    # operation registers the field with Django's migration state without
    # executing any SQL, avoiding a DuplicateColumn error.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="tour",
                    name="cover_image",
                    field=models.ImageField(
                        blank=True, null=True, upload_to="tour_covers/"
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
