# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0008_tour_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Country where the tour is located",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="country_code",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-1 alpha-2 country code for the tour country",
                max_length=2,
            ),
        ),
    ]
