# Generated by Django 5.2.13 on 2026-04-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0008_tour_cover_image"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE tours_tour "
                        "ADD COLUMN IF NOT EXISTS credit_price integer "
                        "NOT NULL DEFAULT 0 CHECK (credit_price >= 0);"
                    ),
                    reverse_sql="ALTER TABLE tours_tour DROP COLUMN IF EXISTS credit_price;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="tour",
                    name="credit_price",
                    field=models.PositiveIntegerField(default=0),
                ),
            ],
        ),
    ]
