# Generated by Django 5.2.13 on 2026-04-23 16:44

import apps.tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0011_remove_puzzleattempt_attempt_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picturecomparepuzzledetail",
            name="reference_image",
            field=models.ImageField(
                upload_to=apps.tours.models.puzzle_reference_image_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="reference_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.tours.models.puzzle_reference_image_upload_to,
            ),
        ),
    ]
