# Generated by Django 5.2.12 on 2026-04-23 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0009_tour_country_tour_country_code"),
        ("tours", "0011_remove_puzzleattempt_attempt_image"),
    ]

    operations = []
