# Generated by Django 5.2.13 on 2026-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0012_alter_picturecomparepuzzledetail_reference_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("preview_image_url", models.URLField()),
                ("scene_asset_url", models.URLField()),
                (
                    "anchors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Anchor definitions with stable ids and xyz coordinates.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
