# Generated by Django 5.2.13 on 2026-04-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_picturecomparepuzzledetail_reference_image_and_more'),
        ('tours', '0012_merge_0009_tour_country_tour_country_code_0011_remove_puzzleattempt_attempt_image'),
    ]

    operations = [
    ]
