# Generated by Django 5.2.13 on 2026-04-23 19:58

import apps.tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0013_armodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="armodel",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.tours.models.ar_model_preview_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="armodel",
            name="scene_asset_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.tours.models.ar_model_scene_asset_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="armodel",
            name="preview_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="armodel",
            name="scene_asset_url",
            field=models.URLField(blank=True),
        ),
    ]
