# Generated by Django 5.2.13 on 2026-04-26 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0013_merge_20260426_1046"),
        ("tours", "0014_armodel_preview_image_armodel_scene_asset_file_and_more"),
    ]

    operations = []
