# Generated by Django 5.2.13 on 2026-04-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0015_merge_20260426_1207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="puzzle_type",
            field=models.CharField(
                choices=[
                    ("TRIVIA", "Trivia"),
                    ("AR", "Augmented Reality"),
                    ("GYROSCOPE", "Gyroscope"),
                    ("PICTURE_COMPARE", "Picture Compare"),
                    ("COMPASS", "Compass"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CompassPuzzleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_heading_degrees", models.PositiveSmallIntegerField(default=0)),
                (
                    "puzzle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compass_detail",
                        to="tours.puzzle",
                    ),
                ),
            ],
        ),
    ]
