# Generated by Codex on 2026-04-30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0016_alter_puzzle_puzzle_type_compasspuzzledetail"),
        ("tours", "0016_tour_is_ai_generated"),
    ]

    operations = []
