# Generated by Django 5.2.13 on 2026-05-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0017_merge_0016_compass_and_ai_generated"),
        ("tours", "0018_merge_20260430_1940"),
    ]

    operations = []
