# Generated by Django 5.2.13 on 2026-04-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0016_alter_puzzle_puzzle_type_compasspuzzledetail"),
        ("tours", "0018_remove_tour_cover_image_url"),
    ]

    operations = []
