# Generated by Django 5.2.13 on 2026-05-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0018_merge_20260430_1940"),
        ("tours", "0019_merge_cover_image_and_compass"),
    ]

    operations = []
