# Generated by Django 5.2.13 on 2026-05-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0019_merge_20260430_0756"),
        ("tours", "0020_merge_20260501_1134"),
    ]

    operations = []
