# Generated by Django 5.2.13 on 2026-05-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0019_merge_20260501_1017"),
        ("tours", "0021_merge_20260501_1151"),
    ]

    operations = []
