# Generated by Django 5.2.13 on 2026-05-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_merge_20260501_1017'),
        ('tours', '0022_tour_generation_source'),
    ]

    operations = [
    ]
