# Generated by Django 5.2.13 on 2026-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0022_merge_20260501_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="puzzle_type",
            field=models.CharField(
                choices=[
                    ("TRIVIA", "Trivia"),
                    ("OPEN_ENDED", "Open Ended"),
                    ("AR", "Augmented Reality"),
                    ("GYROSCOPE", "Gyroscope"),
                    ("PICTURE_COMPARE", "Picture Compare"),
                    ("COMPASS", "Compass"),
                ],
                max_length=20,
            ),
        ),
    ]
