# Generated by Django 5.2.13 on 2026-05-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0022_tour_generation_source"),
        ("tours", "0023_alter_puzzle_puzzle_type"),
    ]

    operations = []
