# Generated by Django 5.2.13 on 2026-05-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tour_credit_price'),
        ('tours', '0025_alter_puzzle_puzzle_type_remove_gyroscope'),
    ]

    operations = [
    ]
