# Generated by Django 5.2.13 on 2026-05-02 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0023_tour_pending_status"),
        ("tours", "0025_alter_puzzle_puzzle_type_remove_gyroscope"),
    ]

    operations = []
