# Generated by Django 5.2.13 on 2026-05-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0026_merge_20260501_2209"),
        ("tours", "0026_merge_20260502_0018"),
    ]

    operations = []

