# Generated by Django 5.2.13 on 2026-05-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetoken",
            name="device_token",
            field=models.CharField(max_length=500),
        ),
    ]
