# Generated by Django 5.2.9 on 2025-12-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="token",
            new_name="credit",
        ),
    ]
