# Generated by Django 5.2.11 on 2026-03-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_banned"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
