# Generated by Django 5.2.12 on 2026-04-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_avatar_url"),
        ("users", "0004_remove_admin_model"),
    ]

    operations = []
