# Generated by Codex on 2026-04-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_merge_20260410_2235"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_type",
                    models.CharField(
                        choices=[("tours", "Tours"), ("users", "Users")],
                        max_length=16,
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("searched_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_search_history",
                "ordering": ["-searched_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="searchhistory",
            constraint=models.UniqueConstraint(
                fields=("user", "search_type", "query"),
                name="unique_user_search_history_query",
            ),
        ),
    ]
