# Generated by Django 5.2.13 on 2026-05-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetotp",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
