# Generated by Django 5.2.13 on 2026-05-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_login_streak_fields"),
        ("users", "0010_passwordresetotp_attempts"),
    ]

    operations = []
