const BAR_HEIGHT = 62;

export const ODYSSEY_TAB_BAR_INNER_PADDING = 4;
export const ODYSSEY_TAB_BAR_HEIGHT = BAR_HEIGHT;
export const ODYSSEY_TAB_BAR_FLOATING_HEIGHT = BAR_HEIGHT;
export const ODYSSEY_TAB_BAR_ACTIVE_CONTENT_COLOR = '#020617';
