# Generated by Django 5.2.12 on 2026-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourprogress",
            name="skip_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tourprogress",
            name="total_xp",
            field=models.IntegerField(default=0),
        ),
    ]
