# Generated by Django 5.2.13 on 2026-04-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_tourprogress_snapshot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourprogress',
            unique_together=set(),
        ),
    ]
