# Generated by Django 5.2.13 on 2026-04-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_tourprogress_wrong_attempt_count'),
        ('gamification', '0005_tourprogress_xp_awarded'),
    ]

    operations = [
    ]
