# Generated by Django 5.2.13 on 2026-05-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0006_merge_20260428_2241"),
        ("gamification", "0006_tourprogress_has_completed_once"),
    ]

    operations = []
