# Generated by Django 5.2.13 on 2026-05-01 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0007_merge_20260501_1018"),
        ("gamification", "0007_userbadgehistory"),
    ]

    operations = []
