# Generated by Django 5.2.13 on 2026-05-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_tourprogress_unique_together'),
        ('gamification', '0008_merge_20260501_1620'),
    ]

    operations = [
    ]
