import { StyleSheet } from 'react-native';
import Colors, { ThemeName } from '@/constants/Colors';
import { Spacing } from '@/constants/Spacing';

export default function getStyles(theme: ThemeName) {
  const color = Colors[theme];
  return StyleSheet.create({
    bottomOverlay: {
      ...StyleSheet.absoluteFillObject,
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
    },
    sheetShadow: {
      flex: 1,
      borderTopLeftRadius: Spacing.xxl,
      borderTopRightRadius: Spacing.xxl,
      shadowColor: color.profileHeaderShadow,
      shadowOffset: { width: 0, height: -8 },
      shadowOpacity: theme === 'dark' ? 0.34 : 0.14,
      shadowRadius: 16,
      elevation: 12,
    },
    bottomPanel: {
      flex: 1,
      overflow: 'hidden',
      borderTopLeftRadius: Spacing.xxl,
      borderTopRightRadius: Spacing.xxl,
      borderWidth: 1,
      borderBottomWidth: 0,
      borderColor: color.borderLight,
      backgroundColor: color.cardSurface,
    },
    grabberPressable: {
      width: '100%',
      minHeight: 92,
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.md,
      paddingBottom: Spacing.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    grabberSurface: {
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 0,
      paddingTop: Spacing.sm,
      paddingBottom: Spacing.sm,
    },
    handleBar: {
      width: 48,
      height: 5,
      backgroundColor: color.primary,
      borderRadius: Spacing.borderRadiusFull,
    },
    sheetHeaderContent: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: Spacing.md,
      gap: Spacing.md,
    },
    sheetHeaderText: {
      flex: 1,
      minWidth: 0,
    },
    sheetEyebrow: {
      color: color.subText,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    sheetTitle: {
      color: color.text,
      fontSize: 15,
      fontWeight: '700',
      marginTop: 2,
    },
    stepBadge: {
      minWidth: 46,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: Spacing.sm,
      paddingVertical: 2,
      borderRadius: Spacing.sm,
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: color.borderLight,
    },
    stepBadgeText: {
      color: color.primary,
      fontSize: 12,
      fontWeight: '800',
    },
    miniProgressTrack: {
      width: '100%',
      height: 5,
      marginTop: Spacing.md,
      marginBottom: Spacing.sm,
      borderRadius: Spacing.borderRadiusFull,
      backgroundColor: color.foregroundSecondary,
    },
    miniProgressFill: {
      height: '100%',
      borderRadius: Spacing.borderRadiusFull,
      backgroundColor: color.primary,
    },
    miniProgressNode: {
      position: 'absolute',
      top: -3,
      width: 11,
      height: 11,
      marginLeft: -5.5,
      borderRadius: Spacing.borderRadiusFull,
      backgroundColor: color.cardSurface,
      borderWidth: 2,
      borderColor: color.foregroundSecondary,
    },
    miniProgressNodeActive: {
      borderColor: color.primary,
      backgroundColor: color.primary,
    },
    navigationContent: {
      flex: 1,
      minHeight: 0,
    },
    skipModalOverlay: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: Spacing.xl,
      backgroundColor: color.backgroundBlack,
    },
    skipModalContainer: {
      width: '100%',
      alignItems: 'center',
      padding: Spacing.xl,
      borderRadius: Spacing.xl,
      backgroundColor: color.foreground,
      shadowColor: color.profileHeaderShadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.26,
      shadowRadius: 16,
      elevation: 10,
    },
    skipModalIcon: {
      width: 64,
      height: 64,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: Spacing.borderRadiusFull,
      marginBottom: Spacing.md,
      backgroundColor: color.star + '24',
    },
    skipModalIconText: {
      color: color.star,
      fontSize: 18,
      fontWeight: '900',
    },
    skipModalTitle: {
      color: color.text,
      fontSize: 20,
      fontWeight: '800',
      textAlign: 'center',
      marginBottom: Spacing.sm,
    },
    skipModalMessage: {
      color: color.subText,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
      marginBottom: Spacing.md,
    },
    skipModalWarning: {
      width: '100%',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: Spacing.md,
      backgroundColor: color.star + '18',
      marginBottom: Spacing.lg,
    },
    skipModalWarningText: {
      color: color.text,
      fontSize: 13,
      fontWeight: '600',
      textAlign: 'center',
      lineHeight: 18,
    },
    skipModalActions: {
      width: '100%',
      flexDirection: 'row',
      gap: Spacing.md,
    },
    skipModalCancelButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.md,
      borderRadius: Spacing.md,
      backgroundColor: color.foregroundSecondary,
    },
    skipModalCancelText: {
      color: color.text,
      fontSize: 15,
      fontWeight: '700',
    },
    skipModalConfirmButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.md,
      borderRadius: Spacing.md,
      backgroundColor: color.error,
    },
    skipModalConfirmText: {
      color: color.white,
      fontSize: 15,
      fontWeight: '800',
    },
  });
}
