import { StyleSheet } from 'react-native';
import Colors from '../../constants/Colors';
import { Spacing } from '../../constants/Spacing';
import { ThemeName } from '../../constants/Colors';

export default function getStyles(theme: ThemeName) {
  const color = Colors[theme];
  return StyleSheet.create({
    container: { flex: 1 },
    map: { ...StyleSheet.absoluteFillObject },
    topOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: 'flex-start' },
    topBar: {
      margin: Spacing.md,
      padding: Spacing.md,
      borderRadius: Spacing.borderRadius,
      backgroundColor: color.foreground,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    title: { color: color.text, fontWeight: '600', fontSize: 18 },
    button: {
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: Spacing.sm,
      backgroundColor: color.foregroundSecondary,
    },
    buttonText: { fontWeight: '500' },

    // Search Here — top-left floating pill
    searchHereButton: {
      position: 'absolute',
      top: 56,
      left: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: color.cardSurface,
      borderRadius: Spacing.borderRadiusFull,
      paddingHorizontal: 16,
      paddingVertical: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.18,
      shadowRadius: 8,
      elevation: 6,
    },
    searchHereText: {
      fontSize: 13,
      fontWeight: '700',
      color: color.primary,
    },
    searchHereButtonDisabled: {
      backgroundColor: color.foreground,
      shadowOpacity: 0.06,
    },
    searchHereTextDisabled: {
      color: color.subText,
    },
    locateMeButton: {
      position: 'absolute',
      top: 212,
      right: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: color.cardSurface,
      borderRadius: 18,
      width: 36,
      height: 36,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.16,
      shadowRadius: 7,
      elevation: 5,
    },

    legendCard: {
      position: 'absolute',
      top: 98,
      right: 16,
      minWidth: 172,
      maxWidth: 210,
      backgroundColor: color.cardSurface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: color.borderLight,
      paddingHorizontal: 10,
      paddingVertical: 9,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 5,
    },
    legendToggleButton: {
      position: 'absolute',
      top: 56,
      right: 16,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: color.cardSurface,
      borderWidth: 1,
      borderColor: color.borderLight,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.14,
      shadowRadius: 7,
      elevation: 5,
    },
    legendTitle: {
      color: color.text,
      fontSize: 12,
      fontWeight: '700',
      marginBottom: 6,
    },
    legendSectionTitle: {
      color: color.subText,
      fontSize: 10,
      fontWeight: '700',
      marginTop: 2,
      marginBottom: 5,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    legendRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: 4,
      columnGap: 8,
      rowGap: 6,
    },
    legendItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    legendIconBadge: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: color.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    legendColorDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: color.background,
    },
    legendText: {
      color: color.text,
      fontSize: 10,
      fontWeight: '600',
    },

    // Results bar — collapsed peek at the bottom
    resultsBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: color.cardSurface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingBottom: 28,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 10,
    },
    resultsBarHandle: {
      width: 36,
      height: 4,
      backgroundColor: color.borderLight,
      borderRadius: Spacing.borderRadiusFull,
      marginTop: 10,
      marginBottom: 10,
    },
    resultsBarRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      paddingHorizontal: Spacing.lg,
      gap: Spacing.md,
    },
    resultsBarIconBox: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: color.primaryMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    resultsBarText: {
      flex: 1,
      fontSize: 15,
      fontWeight: '700',
      color: color.text,
    },
    resultsBarSubText: {
      fontSize: 12,
      color: color.subText,
      marginTop: 1,
    },
  });
}
