name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  backend:
    name: Backend (Django)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: |
            backend/requirements/base.txt
            backend/requirements/dev.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          if [ -f requirements/base.txt ]; then pip install -r requirements/base.txt; fi

          if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

  frontend:
    name: Frontend (React Native)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "mobile/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Prebuild Expo Types
        run: |
          npx expo export -p ios --output-dir ./dist-temp-ios
          npx expo export -p android --output-dir ./dist-temp-android
          rm -rf ./dist-temp-ios ./dist-temp-android
        
      - name: Lint (ESLint)
        run: npm run lint

      - name: Format check (Prettier)
        run: npm run format:check

      - name: Type check (TS)
        run: npm run type-check