name: Deploy Odyssey

on:
  push:
    branches:
      - main
      - testing 
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        # If branch is main, use 'latest'. Otherwise, use 'testing'.
        run: |
          if [[ ${{ github.ref_name }} == 'main' ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=testing" >> $GITHUB_ENV
          fi

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: odyssey-hcf3h4fwgkfudpbj.azurecr.io
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      - name: Build and Push
        run: |
          docker build -t odyssey-hcf3h4fwgkfudpbj.azurecr.io/odyssey-backend:${{ env.TAG }} ./backend
          docker push odyssey-hcf3h4fwgkfudpbj.azurecr.io/odyssey-backend:${{ env.TAG }}

      - name: Set deploy metadata
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
            echo "REVISION_SUFFIX=prod-${{ github.run_number }}" >> $GITHUB_ENV
          else
            echo "TAG=testing" >> $GITHUB_ENV
            echo "REVISION_SUFFIX=test-${{ github.run_number }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name odyssey-api \
            --resource-group odyssey \
            --image odyssey-hcf3h4fwgkfudpbj.azurecr.io/odyssey-backend:${TAG} \
            --revision-suffix "${REVISION_SUFFIX}"